apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-sample
  namespace: argocd
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      namespace: apps
    path: cicd/argocd/overlays/test
    repoURL: git@github.com:pledo/challenge-cloud-engineer-lanxess.git
    targetRevision: 'develop'
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
