apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-sample
  namespace: argocd
spec:
  destination:
    namespace: apps
    server: https://springboot-sample.example.com
  project: default
  source:
    kustomize:
      namespace: apps
    path: argocd/overlays/prod
    repoURL: git@github.com:pledo/challenge-cloud-engineer-lanxess.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
