apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: apps

labels:
- includeTemplates: true
  pairs:
    env: prod

patches:
- path: deployment.yaml
- path: ingress.yaml
- path: service.yaml

images:
- name: pledo/springboot-sample
  newTag: v1
