apiVersion: v1
kind: Service
metadata:
  name: sample-app
spec:
  selector:
    app: sample-app
  ports:
    - name: app-port
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP