apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
#- configmap.yaml
#- secrets.yaml


labels:
  - pairs:
      app: springboot-sample

images:
- name: pledo/springboot-sample
  newTag: latest
